run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/bohdanch-w/wheel
  cyclop:
    max-complexity: 30
  wrapcheck:
    ignoreSigs:
      - web.Respond
      - web.Abort
      - web.NewError
      - fmt.Errorf

linters:
  enable-all: true
  disable:    
    - gci
    - paralleltest
    - varnamelen
    - nolintlint
    - ireturn
    - exhaustruct
    - depguard
  
    # deprecated
    - execinquery
    - gomnd
    