run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/bohdanch-w/datatypes
  cyclop:
    max-complexity: 30
  dupl:
    threshold: 200

linters:
  enable-all: true
  disable:    
    - gci
    - paralleltest
    - varnamelen
  
    # deprecated
    - structcheck
    - varcheck
    - ifshort
    - deadcode
    - nosnakecase
    - interfacer
    - maligned
    - scopelint
    - golint
    - exhaustivestruct
    
    # unsupported generics
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
